config/routes.rb
Marketplace::Application.routes.draw do
  root 'static_pages#home'
  resources :items
  get "organizations/index"
  get "organizations/new"
  get "organizations/create"
  get "organizations/show"
  get "transactions/index"
  get "transactions/new"
  get "transactions/create"
  get "transactions/show"
  get "sellers/index"
  get "sellers/new"
  get "sellers/create"
  get "new/create"
  get "new/index"

end

app/models/buyer.rb
class Buyer < ActiveRecord::Base
	has_many :transactions 
	has_many :sellers, through: :transactions
end

app/models/item.rb
class Item < ActiveRecord::Base
	belongs_to :seller
	belongs_to :organization
	has_one :transaction
	has_one :buyer, through: :transactions

	def seller()
		Item.find(2).seller_id
	end


	# Item.create_transaction(params[:buyer_id], seller_id())
end

app/models/organization.rb
class Organization < ActiveRecord::Base
end

app/models/seller.rb
class Seller < ActiveRecord::Base
	has_many :transactions
	has_one :buyer, through: :transactions
	has_many :items
end

app/models/transaction.rb
class Transaction < ActiveRecord::Base
  belongs_to :buyer
  belongs_to :seller
  belongs_to :item
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def new
    @item = Item.new
  end

  def create
  end

  def show
    @item = Item.find(params[:id])
  end
end

app/controllers/organizations_controller.rb
class OrganizationsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end
end

app/controllers/sellers_controller.rb
class SellersController < ApplicationController
  def index
  end

  def new
  end

  def create
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/controllers/transactions_controller.rb
class TransactionsController < ApplicationController
  def index
  end

  def new
  end

  def create
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/organizations_helper.rb
module OrganizationsHelper
end

app/helpers/sellers_helper.rb
module SellersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/items/create.html.erb
<h1>Items#create</h1>
<p>Find me in app/views/items/create.html.erb</p>

app/views/items/index.html.erb
<h2>Current Inventory</h2>
<% @items.each do |x| %>
  <div class="item">
    <h4><%= x.name %></h4>
    <p><%= x.price %></p>
    <p><%= x.description %></p>
    <%= link_to "Show Details", item_path(x.id) %>
  </div>
  <% end %>

app/views/items/new.html.erb
<h1>Post an Item</h1>
  <%= form_for @item do |f| %>
    <%= f.label "Item Name" %>
    <%= f.text_field :name %><br>
    <%= f.label "Price" %>
    <%= f.number_field :price, :class => 'text_field', :step => "any" %><br>
    <%= f.label "Description" %>
    <%= f.text_area :description %><br>
    <%= f.label "Organization" %>
    <%= f.select :organization, [["Connect 2 Good"], ["Austin Pets Alive"]] %>
    <%= f.label "Percent of Proceeds to Donate" %>
    <%= f.select :percent, [[100], [50], [20], [10]] %><br>
    <%= f.label "Upload a photo" %>
    <%= f.file_field :photo1 %><br>
    <%= f.label "Optional photo" %>
    <%= f.file_field :photo2 %><br>
    <%= f.label "Optional photo" %>
    <%= f.file_field :photo3 %><br>
    <%= f.check_box :agreement %><%=f.label "I agree to complete this transaction through Connect 2 Good so that the proceeds can be donated to the non-profit I have indicated above." %><br>
    <%= f.submit "Submit" %>

    <% end %>

app/views/items/show.html.erb
<h3><%= @item.name %></h3>
<p>$<%= @item.price %></p>
<p><%= @item.description %></p>


<%= link_to "Contact Seller" %>
<%= link_to "Buy Item" %><br>
<br>
<%= link_to "Back", items_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Marketplace</title>
  <%= stylesheet_link_tag    "application", media: "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<h1>Connect 2 Good Marketplace</h1>
<%= yield %>

</body>
</html>

app/views/organizations/create.html.erb
<h1>Organizations#create</h1>
<p>Find me in app/views/organizations/create.html.erb</p>

app/views/organizations/index.html.erb
<h1>Organizations#index</h1>
<p>Find me in app/views/organizations/index.html.erb</p>

app/views/organizations/new.html.erb
<h1>Organizations#new</h1>
<p>Find me in app/views/organizations/new.html.erb</p>

app/views/organizations/show.html.erb
<h1>Organizations#show</h1>
<p>Find me in app/views/organizations/show.html.erb</p>

app/views/sellers/create.html.erb
<h1>Sellers#create</h1>
<p>Find me in app/views/sellers/create.html.erb</p>

app/views/sellers/index.html.erb
<h1>Sellers#index</h1>
<p>Find me in app/views/sellers/index.html.erb</p>

app/views/sellers/new.html.erb
<h1>Sellers#new</h1>
<p>Find me in app/views/sellers/new.html.erb</p>

app/views/static_pages/home.html.erb
<h3>Connect2Good Marketplace</h3>
<%= link_to "Sell Item", new_item_path %>
<%= link_to "Buy Items", items_path %>

app/views/transactions/create.html.erb
<h1>Transactions#create</h1>
<p>Find me in app/views/transactions/create.html.erb</p>

app/views/transactions/index.html.erb
<h1>Transactions#index</h1>
<p>Find me in app/views/transactions/index.html.erb</p>

app/views/transactions/new.html.erb
<h1>Transactions#new</h1>
<p>Find me in app/views/transactions/new.html.erb</p>

app/views/transactions/show.html.erb
<h1>Transactions#show</h1>
<p>Find me in app/views/transactions/show.html.erb</p>